apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
   push: false
  # googleCloudBuild:
  #  projectId: ticketing-dev-377423
  artifacts:
    - image: guisaez/auth # us.gcr.io/ticketing-dev-377423/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: guisaez/client # us.gcr.io/ticketing-dev-377423/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: '**/*.js'
            dest: .
    - image: guisaez/tickets # us.gcr.io/ticketing-dev-377423/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: guisaez/orders # us.gcr.io/ticketing-dev-377423/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: guisaez/expiration # us.gcr.io/ticketing-dev-377423/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: guisaez/payments # us.gcr.io/ticketing-dev-377423/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
            