apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: us.gcr.io/ticketing-dev-377423/client
          env:
            - name: STRIPE_PUB_KEY
              value: 'pk_test_51Mr0ytLpkiXGmtRLfvAeDk8gjMfpBGtJ6TXhpG5aXRVla1apUnEN5dBuVUfcnCsRWMWEZ3iN2G4CgqHPrpnePkZf00O99DeaVR'

---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
